In [1]:
import pickle
import numpy as np
import pandas as pd
import talib

In [2]:
random_universes = pickle.load(open("random_universes.pickle", "rb"))

In [4]:
close = random_universes[0]["close"]
open = random_universes[0]["open"]
low = random_universes[0]["low"]
high = random_universes[0]["high"]
volume = random_universes[0]["volume"]

In [44]:
momentum = close.apply(lambda x: talib.MOM(x, timeperiod=14))
momentum.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,-0.01360,53.2,-17.3,-5.53,0.011,-0.6043,-1.735,1.626,-0.505,NaN,...,0.00799,-4.82,-2.847,NaN,NaN,-84.9,-0.02056,-43.0,-0.00557,-0.01002
2021-09-27,-0.01004,44.8,-23.3,1.35,-0.002,-0.4919,-0.311,1.239,-0.340,NaN,...,0.00760,-3.95,-2.636,NaN,NaN,-64.8,-0.01841,-39.9,-0.00465,-0.00800
2021-09-28,-0.01480,12.6,-31.8,-14.11,-0.004,-0.4747,1.069,0.823,-0.414,NaN,...,0.02040,-8.70,-3.203,NaN,NaN,-104.5,-0.02683,-45.6,-0.00464,-0.01054
2021-09-29,-0.01595,11.4,-23.0,-10.61,0.008,-0.4083,0.104,0.630,-0.504,NaN,...,0.01754,-7.82,-3.617,NaN,NaN,-172.7,-0.02839,-54.8,-0.00419,-0.01139
2021-09-30,-0.00224,19.3,-32.0,-14.21,-0.002,-0.4105,-0.479,0.573,-0.341,NaN,...,0.01258,-5.80,-3.275,NaN,NaN,-130.4,-0.02110,-45.8,-0.00317,-0.00798

In [17]:
def get_macd(close:np.ndarray)->np.ndarray:

    macd, _, _ = talib.MACD(close, fastperiod=12, slowperiod=26)

    return macd

In [43]:
macd = close.apply(get_macd)
macd.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,-0.003690,10.641301,-7.683820,-1.189801,0.001326,0.105865,NaN,0.111547,-0.235243,NaN,...,NaN,-0.939703,-0.926247,NaN,NaN,-45.937939,-0.006843,-19.412815,-0.000706,-0.001945
2021-09-27,-0.003776,10.807663,-8.665889,-1.292358,0.001104,0.085761,NaN,0.175817,-0.233081,NaN,...,NaN,-1.066625,-0.970341,NaN,NaN,-47.167868,-0.007139,-19.793841,-0.000829,-0.002149
2021-09-28,-0.004042,10.120822,-9.480150,-1.617241,0.000677,0.060384,NaN,0.201033,-0.226577,NaN,...,NaN,-1.226502,-1.027095,NaN,NaN,-48.718748,-0.007668,-20.018362,-0.000933,-0.002408
2021-09-29,-0.004172,9.435453,-8.669897,-1.675457,0.001054,0.043149,NaN,0.201906,-0.214831,NaN,...,NaN,-1.277956,-1.043183,NaN,NaN,-49.083470,-0.007945,-20.069843,-0.000943,-0.002546
2021-09-30,-0.003165,8.870728,-8.215483,-1.178669,0.000778,0.030797,NaN,0.194067,-0.197755,NaN,...,NaN,-1.211968,-1.024914,NaN,NaN,-46.895334,-0.007722,-19.442715,-0.000952,-0.002453

In [42]:
mfi = close.apply(lambda x: talib.MFI(high.loc[x.index, x.name], low.loc[x.index, x.name], x, volume.loc[x.index, x.name]))
mfi.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,46.477548,92.873315,77.399458,85.552500,80.255734,27.536460,31.518089,98.111956,39.605949,0.0,...,49.223064,46.497545,34.063370,0.0,0.0,74.428724,38.159135,48.353187,62.302885,36.751338
2021-09-27,52.504408,90.886857,81.328449,87.018814,68.879348,38.505902,41.737362,72.469940,50.003667,0.0,...,49.514923,50.360635,40.091488,0.0,0.0,76.267131,40.063477,52.114715,65.709082,41.996835
2021-09-28,45.733998,89.037703,78.535691,60.013151,63.133069,41.482423,52.602302,69.915885,50.094011,0.0,...,55.029840,42.522154,34.647785,0.0,0.0,75.507446,34.738565,43.931701,65.794976,36.254922
2021-09-29,41.126736,88.750115,81.750490,71.897224,58.663568,46.540594,47.782326,68.789491,44.981989,0.0,...,52.808162,37.257628,32.627295,0.0,0.0,34.805277,28.882636,38.281434,75.621498,31.139370
2021-09-30,89.687287,88.733219,82.309034,60.858197,64.138962,36.343353,43.789134,67.781273,52.141746,0.0,...,47.978117,45.713396,28.831156,0.0,0.0,45.123747,33.947219,27.404518,74.309066,38.423614

In [41]:
natr = close.apply(lambda x: talib.NATR(high.loc[x.index, x.name], low.loc[x.index, x.name], x))
natr.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,12.742301,16.617038,9.705531,18.421414,0.956291,15.508038,NaN,28.435146,14.342206,NaN,...,NaN,12.744011,15.971032,NaN,NaN,16.329084,13.288343,17.170847,16.692025,16.634415
2021-09-27,12.245017,18.245840,11.452706,18.152577,1.208788,16.090445,NaN,36.688826,14.188265,NaN,...,NaN,13.430604,16.166747,NaN,NaN,16.644031,13.393228,16.982466,16.470098,16.321496
2021-09-28,13.390492,18.936581,11.082026,18.281128,1.391174,16.739264,NaN,39.580669,13.609558,NaN,...,NaN,13.550409,16.417168,NaN,NaN,16.527957,13.623620,16.292941,16.213119,16.788130
2021-09-29,12.765454,18.333694,11.023763,17.477815,1.493456,16.027464,NaN,41.779940,13.208566,NaN,...,NaN,12.769717,15.650494,NaN,NaN,15.697136,13.076123,15.837232,15.985029,15.853366
2021-09-30,13.541388,17.292213,11.415331,15.396131,1.468079,15.089730,NaN,41.327978,12.103743,NaN,...,NaN,11.789418,14.442276,NaN,NaN,14.633626,11.953205,14.660979,15.689483,14.245246

In [40]:
htdcp = close.apply(talib.HT_DCPHASE)
htdcp.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,-7.555580,179.688782,299.803687,293.482519,85.823879,280.031146,NaN,49.916964,-18.316823,NaN,...,NaN,11.043912,-0.880736,NaN,NaN,-33.088512,-0.124001,NaN,0.034076,-7.436671
2021-09-27,-1.549026,180.996418,-44.654150,-37.866671,112.290833,297.973968,NaN,77.452693,-13.892627,NaN,...,NaN,35.848524,8.745035,NaN,NaN,-23.099251,8.476874,NaN,6.703455,-4.159978
2021-09-28,7.244642,183.492427,-23.651148,-19.428086,136.817675,-42.411170,NaN,93.157690,-4.894727,NaN,...,NaN,45.472227,16.694632,NaN,NaN,-6.130825,15.089112,NaN,0.739986,-0.577903
2021-09-29,16.364060,185.184338,-7.020285,11.669456,154.786026,-38.893013,NaN,104.317311,5.687702,NaN,...,NaN,50.669351,23.554327,NaN,NaN,6.930418,19.218481,NaN,1.583944,3.553236
2021-09-30,30.217281,192.236002,16.056674,30.646073,178.849520,-18.413672,NaN,113.475921,17.045609,NaN,...,NaN,53.443296,28.677272,NaN,NaN,20.240262,24.220337,NaN,3.095830,8.939610

In [25]:
def get_ht_sine(close:np.ndarray):

    sine, _ = talib.HT_SINE(close)

    return sine

In [38]:
hts = close.apply(get_ht_sine)
hts.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,-0.131488,0.005432,-0.867733,-0.917182,0.997345,-0.984713,NaN,0.765112,-0.314271,NaN,...,NaN,0.191561,-0.015371,NaN,NaN,-0.545934,-0.002164,NaN,0.000595,-0.129430
2021-09-27,-0.027032,-0.017390,-0.702826,-0.613826,0.925270,-0.883161,NaN,0.976117,-0.240103,NaN,...,NaN,0.585644,0.152038,NaN,NaN,-0.392325,0.147410,NaN,0.116731,-0.072542
2021-09-28,0.126106,-0.060917,-0.401167,-0.332623,0.684322,-0.674446,NaN,0.998482,-0.085325,NaN,...,NaN,0.712911,0.287271,NaN,NaN,-0.106799,0.260321,NaN,0.012915,-0.010086
2021-09-29,0.281740,-0.090360,-0.122221,0.202265,0.426000,-0.627868,NaN,0.968941,0.099106,NaN,...,NaN,0.773501,0.399618,NaN,NaN,0.120664,0.329171,NaN,0.027642,0.061976
2021-09-30,0.503281,-0.211939,0.276588,0.509733,0.020078,-0.315875,NaN,0.917228,0.293133,NaN,...,NaN,0.803268,0.479876,NaN,NaN,0.345958,0.410247,NaN,0.054006,0.155393

In [39]:
httmm = close.apply(talib.HT_TRENDMODE)
httmm.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
2021-09-27,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
2021-09-28,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
2021-09-29,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1
2021-09-30,1,1,1,1,0,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,1

In [35]:
obv = close.apply(lambda x: talib.OBV(x, volume.loc[x.index, x.name]))
obv.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,5.433239e+08,6.634999e+07,3.521737e+06,1.304509e+08,-2.917797e+06,8.558198e+08,-1.126742e+08,3.048892e+08,1.457404e+09,-6.271925e+06,...,-3.240274e+08,3.373329e+09,-4.818900e+07,7.658997e+07,4.183051e+06,8.045877e+07,1.676207e+09,6.137525e+07,9.015023e+07,1.298873e+09
2021-09-27,5.447958e+08,6.096400e+07,-2.647365e+06,1.340613e+08,-3.556818e+06,7.195892e+08,-1.116674e+08,1.775822e+08,1.464938e+09,-6.271925e+06,...,-3.230273e+08,3.236163e+09,-4.909399e+07,7.658997e+07,4.183051e+06,7.932315e+07,1.668013e+09,6.080932e+07,8.912017e+07,1.294405e+09
2021-09-28,5.426640e+08,5.766388e+07,-3.958929e+06,1.327082e+08,-4.239947e+06,6.165443e+08,-1.100541e+08,1.567197e+08,1.469770e+09,-6.271925e+06,...,-3.217210e+08,3.091835e+09,-4.954919e+07,7.658997e+07,4.183051e+06,7.918419e+07,1.661106e+09,6.027751e+07,8.760866e+07,1.289734e+09
2021-09-29,5.437811e+08,5.479835e+07,5.729492e+06,1.357027e+08,-3.897900e+06,7.198652e+08,-1.110338e+08,1.443239e+08,1.475096e+09,-6.271925e+06,...,-3.232477e+08,3.215064e+09,-4.850872e+07,7.658997e+07,4.183051e+06,7.939202e+07,1.667309e+09,5.976770e+07,1.044844e+08,1.294364e+09
2021-09-30,6.128377e+08,5.619416e+07,2.950949e+06,1.364687e+08,-3.996034e+06,7.947787e+08,-1.119352e+08,1.324123e+08,1.477571e+09,-6.271925e+06,...,-3.245168e+08,3.347972e+09,-4.783045e+07,7.658997e+07,4.183051e+06,7.974758e+07,1.673064e+09,6.039649e+07,1.012445e+08,1.301791e+09

In [34]:
co = close.apply(lambda x: talib.ADOSC(high.loc[x.index, x.name], low.loc[x.index, x.name], x, volume.loc[x.index, x.name]))
co.tail()

,STPTUSDT,MLNBUSD,CREAMBUSD,TORNBUSD,SUSDUSDT,ALGOUSDT,XTZDOWNUSDT,CVPBUSD,BAKEBUSD,BULLUSDT,...,LINKDOWNUSDT,LINKUSDT,UNFIBUSD,BCHABUSD,DAIUSDT,QUICKBUSD,RVNUSDT,FARMBUSD,CKBBUSD,STMXUSDT
date,,,,,,,,,,,,,,,,,,,,,
2021-09-26,-1.559932e+05,-3.014399e+07,-5.542852e+06,-2.062506e+06,92834.608394,-1.799278e+07,4.176714e+04,-5.026374e+07,-1.476304e+05,3.725290e-08,...,-1.265774e+06,8.460773e+07,28561.748550,42.389189,4.656613e-10,-1.121091e+06,-1.155971e+06,-1.815117e+06,-3.108980e+06,2.122588e+06
2021-09-27,-1.758068e+05,-2.680542e+07,-6.600604e+06,-2.543424e+06,45387.050480,-4.081133e+07,6.072574e+05,-9.803692e+07,-1.145587e+06,3.725290e-08,...,-1.156770e+06,6.318295e+07,-183619.096745,34.682064,4.656613e-10,-1.292516e+06,-3.740845e+06,-1.767535e+06,-2.781157e+06,8.297037e+05
2021-09-28,-8.240704e+05,-2.315446e+07,-6.463075e+06,-2.919397e+06,-78017.075996,-7.451681e+07,1.245574e+06,-1.144104e+08,-2.233993e+06,3.725290e-08,...,-6.273413e+05,8.000221e+06,-379589.557463,28.376234,4.656613e-10,-1.284867e+06,-6.363518e+06,-1.614825e+06,-2.252224e+06,-1.072305e+06
2021-09-29,-1.111060e+06,-2.018403e+07,-5.998758e+06,-3.307077e+06,-121408.120828,-9.574731e+07,1.353154e+06,-1.137940e+08,-3.270147e+06,3.725290e-08,...,-3.327304e+05,-2.020295e+07,-573706.793143,23.216919,4.656613e-10,-1.194892e+06,-7.771396e+06,-1.527209e+06,-4.018697e+06,-2.004834e+06
2021-09-30,-6.344496e+06,-1.736769e+07,-6.054489e+06,-2.947020e+06,-153101.305584,-9.035782e+07,9.873502e+05,-1.058285e+08,-2.689989e+06,3.725290e-08,...,-3.891580e+05,-7.752536e+06,-504920.492149,18.995661,4.656613e-10,-9.563807e+05,-5.809602e+06,-1.315623e+06,-4.707361e+06,-6.286638e+05

In [50]:
features_df = [("momentum", momentum), ("macd", macd), ("mfi", mfi), ("natr", natr), ("htdcp", htdcp), ("hts", hts), ("httmm", httmm), ("on_balance_vol", obv)]
df = co.stack().reset_index().rename({"level_1": "symbol", 0: "chaikin_oscillator"}, axis=1)
for feature_name, feature_df in features_df:
    tmp = feature_df.stack().reset_index().rename({"level_1": "symbol", 0: feature_name}, axis=1)
    df = df.merge(tmp, how="inner", on=["date", "symbol"])
df.head()

,date,symbol,chaikin_oscillator,momentum,macd,mfi,natr,htdcp,hts,httmm,on_balance_vol
0,2019-07-04,IOTAUSDT,4.241596e+05,-0.02990,-0.006789,56.159158,8.700345,294.548224,-0.909612,1,2.306950e+07
1,2019-07-04,CELRUSDT,-5.354098e+06,-0.00214,0.000015,53.328508,15.392703,35.468398,0.580254,1,7.254157e+07
2,2019-07-04,LINKUSDT,2.220887e+06,1.68740,0.601003,62.933848,14.153364,169.004665,0.190729,1,4.611323e+08
3,2019-07-05,IOTAUSDT,1.646111e+05,-0.04090,-0.008563,52.937086,8.405624,305.338140,-0.815753,1,2.192511e+07
4,2019-07-05,CELRUSDT,-4.667581e+06,0.00020,0.000046,59.167614,14.301088,47.596538,0.738415,0,7.517409e+07

In [51]:
df.shape

(15546, 11)

In [61]:
from typing import Optional
def create_target(close:pd.DataFrame, n:int=1, target_type:str="binary", q:Optional[int]=None):
    target = (close.shift(-n)/close) - 1.
    target = target.stack().reset_index().rename({"level_1": "symbol", 0: "target"}, axis=1)
    if target_type == "binary":
        if q is None:
            target.loc[:, "target"] = target.loc[:, "target"].apply(lambda x: 1 if x>0 else 0)
        else:
            target.loc[:, "target"] = target.groupby("date").apply(lambda x: pd.qcut(x["target"], q=q, labels=False)).values
            target.loc[:, "target"] = target.loc[:, "target"].apply(lambda x: 1 if x == q-1 else 0)
    else:
        if q is None:
            raise ValueError("q must be provided if target_type='multi'")
        target.loc[:, "target"] = target.groupby("date").apply(lambda x: pd.qcut(x["target"], q=q, labels=False)).values
    
    return target

In [62]:
target = create_target(close, target_type="multi", q=5)

In [64]:
df.shape

(15546, 11)

In [67]:
df = df.merge(target, on=["date", "symbol"], how="left")

In [68]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.drop(["date", "symbol", "target"], axis=1))
pca = PCA(n_components=0.95)
X_scaled_pca = pca.fit_transform(X_scaled)
df_transformed = df.loc[:, ["date", "symbol", "target"]].copy()
df_transformed.loc[:, range(X_scaled_pca.shape[1])] = X_scaled_pca
df_transformed.head()

,date,symbol,target,0,1,2,3,4,5,6,7
0,2019-07-04,IOTAUSDT,0.0,-0.739849,1.816024,-1.212968,0.374425,0.469668,-0.266447,-0.529391,-0.276699
1,2019-07-04,CELRUSDT,3.0,0.461301,-1.246907,0.145234,-0.464866,0.026136,-0.311463,-0.071852,-0.109766
2,2019-07-04,LINKUSDT,2.0,-0.184868,0.241969,0.294417,-0.149017,0.332166,0.013579,0.156146,-0.363376
3,2019-07-05,IOTAUSDT,3.0,-0.717965,1.760825,-1.228021,0.392877,0.421515,-0.304933,-0.545122,-0.531667
4,2019-07-05,CELRUSDT,1.0,0.208570,-0.847061,-0.209206,-1.210763,-3.191226,1.582067,0.526760,0.054123

In [69]:
import pywt

In [130]:
haar = pywt.Wavelet("haar")
features = []

for name, group in df_transformed.groupby("symbol"):
    group_ = group.reset_index(drop=True)
    for c in df_transformed.drop(["date","symbol", "target"], axis=1).columns:
        ca, cd1, cd2 = pywt.wavedec(group_.loc[:, c].values, haar, mode="periodization", level=2)
        cd1 = np.where(cd1 >= 2.*cd1.std(ddof=1, axis=0), 0., cd1)
        cd2 = np.where(cd2 >= 2.*cd2.std(ddof=1, axis=0), 0., cd2)
        cd3 = np.where(cd3 >= 2.*cd3.std(ddof=1, axis=0), 0., cd3)
        denoised_signal = pywt.waverec([ca, cd1, cd2], haar)
        group_.loc[:, c] = denoised_signal[1:] if len(group_)%2 != 0 else denoised_signal
    features.append(group_)

In [137]:
df_transformed_denoised = pd.concat(features, ignore_index=True).sort_values("date").dropna(axis=0, subset=["target"])

In [146]:
df_transformed.dropna(axis=0, subset=["target"], inplace=True)

In [147]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

rf = RandomForestClassifier()
X = df_transformed.drop(["date", "symbol", "target"], axis=1).values
y = df_transformed.loc[:, "target"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
rf.fit(X_train, y_train)

RandomForestClassifier()

In [148]:
from sklearn.metrics import classification_report

print(classification_report(y_test, rf.predict(X_test)))

              precision    recall  f1-score   support

         0.0       0.25      0.24      0.25       937
         1.0       0.21      0.22      0.22       927
         2.0       0.20      0.21      0.20       925
         3.0       0.21      0.21      0.21       940
         4.0       0.21      0.21      0.21       922

    accuracy                           0.22      4651
   macro avg       0.22      0.22      0.22      4651
weighted avg       0.22      0.22      0.22      4651

# Universes

In [1]:
from trading_gym.envs.data_loader import CryptoData
from datetime import datetime 

start = datetime(2019, 5, 1)
end = datetime(2021, 9, 30)

cd = CryptoData()

supported_symbols = cd.supported_symbols

symbols_filtered = [
    symbol
    for symbol in supported_symbols
    if (
        symbol.endswith("USDT")
        or symbol.endswith("BUSD")
        or symbol.endswith("USDC")
    )
    and not symbol.startswith("USDT")
    and not symbol.startswith("USDS")
    and not symbol.startswith("BUSD")
    and not symbol.startswith("USDC")
    and not symbol.startswith("TUSD")
    and not symbol.startswith("DAI")
    and not symbol.startswith("PAX")
    and not symbol.startswith("EUR")
    and not symbol.startswith("MDX")
    and symbol not in ["UNIDOWNUSDT",      
"LTCDOWNUSDT",      
"SUSHIDOWNUSDT",    
"ETHDOWNUSDT",      
"BNBDOWNUSDT",      
"XLMDOWNUSDT",       
"SXPDOWNUSDT",       
"TRXDOWNUSDT",       
"YFIDOWNUSDT",       
"XTZDOWNUSDT",       
"AAVEDOWNUSDT",      
"DOTDOWNUSDT",       
"LINKDOWNUSDT",      
"ADADOWNUSDT",       
"XRPDOWNUSDT",        
"COCOSUSDT",]
]

symbols = {}

for symbol in symbols_filtered:

    if "USDT" in symbol:
        quote = "USDT"
    elif "BUSD" in symbol:
        quote = "BUSD"
    elif "USDC" in symbol:
        quote = "USDC"
    else:
        continue

    s = symbol.replace(quote, "")
    if s in symbols:
        continue
    else:
        symbols[s] = symbol

symbols = list(symbols.values())

print("Downloading data")

assets_data = cd.get_data(start=start, end=end, universe=symbols)

symbols = list(filter(lambda s: s in assets_data["close"].columns, symbols))

Downloading data

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 383/383 [00:06<00:00, 58.26it/s]

In [6]:
assets_data["close"].pct_change().max().sort_values(ascending=False).head(20)

UNIDOWNUSDT      127058.676250
LTCDOWNUSDT      119584.987261
SUSHIDOWNUSDT    118688.485628
ETHDOWNUSDT      111948.152542
BNBDOWNUSDT      106943.441259
XLMDOWNUSDT       97069.411153
SXPDOWNUSDT       95137.075085
TRXDOWNUSDT       72940.666667
YFIDOWNUSDT       69413.705882
XTZDOWNUSDT       50185.809958
AAVEDOWNUSDT      14722.303797
DOTDOWNUSDT       13607.613333
LINKDOWNUSDT      11996.033493
ADADOWNUSDT       10564.163009
XRPDOWNUSDT        8833.592593
COCOSUSDT          1294.395683
DREPUSDT            106.577602
COVERBUSD             5.849423
PROMBUSD              5.163156
DOGEUSDT              3.924114
dtype: float64